/******************************************************************************
 *
 * Module: ULTRASONIC
 *
 * File Name: ultrasonic.c
 *
 * Description: Source file for the ULTRASONIC driver
 *
 * Author: Mohamed Ahmed kamal
 *
 *******************************************************************************/
#include "ultrasonic.h"
#include "gpio.h"
#include"icu.h"
#include<util/delay.h>
/*******************************************************************************
 *                           Global Variables                                  *
 *******************************************************************************/
 static uint16 ultrasonic_time = 0;
 static uint8 edge_count = 0;
/********************************************************************************/

void Ultrasonic_Init(void)
{

	/* Create configuration structure for ICU driver */
	Icu_ConfigType Icu_Config = {F_CPU_8,RISING};

	Icu_init(&Icu_Config); /*Initialize the ICU driver*/

	Icu_setCallBack(Ultrasonic_edgeProcessing); /*Setup the ICU call back function*/

	GPIO_setupPinDirection(PORTB_ID,PIN5_ID,PIN_OUTPUT); /*Setup the direction for the trigger pin as output*/
}

void Ultrasonic_Trigger(void)
{
	/*Send the Trigger pulse to the ultrasonic*/

	GPIO_writePin(PORTB_ID,PIN5_ID,LOGIC_HIGH);  /*the raising edge of trigger*/
	_delay_us(10);                               /*trigger pulse width*/
	GPIO_writePin(PORTB_ID,PIN5_ID,LOGIC_LOW);   /*the falling edge of trigger*/
}

uint16 Ultrasonic_ReadDistance(void)
{
	uint16 Distance;
	Ultrasonic_Trigger();                /*Send the trigger pulse*/
	while(ultrasonic_time==0);           /*waiting for pulse time generated by ultrasonic sensor */
	Distance= ultrasonic_time/59;        /* calculating distance using pulse time */

	return(Distance);
}

void Ultrasonic_edgeProcessing(void)
{
	edge_count++; /*start from first edge*/
		if(edge_count == 1)
		{
			 /* Clear the timer counter register to start measurements from the
			 * first detected rising edge */
			Icu_clearTimerValue();

			/* Detect falling edge */
			Icu_setEdgeDetectionType(FALLING);
		}
		else if(edge_count == 2) /* check if the second edge came  */
		{
			ultrasonic_time = Icu_getInputCaptureValue(); /* read time calculated from timer */
		}
}

